version: "3"
services:
    jupyter:
        build: .
        volumes:
            - $PWD:/tmp/working
        working_dir: /tmp/working
        ports:
            - 8889:8889
        command: jupyter notebook --port=8889 --ip=0.0.0.0 --allow-root
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]